void intializing_textures()
{
	// Load the textures for the fox's animations and set the initial texture and position of the fox sprite
	Fox_walking.loadFromFile("MAIN/My-Fox/Animals/Fox/Fox_Walk_with_shadow.png");
	Fox_running.loadFromFile("MAIN/My-Fox/Animals/Fox/Fox_Run_with_shadow.png");
	Fox_idle.loadFromFile("MAIN/My-Fox/Animals/Fox/Fox_Idle_with_shadow.png");
	Fox.setTexture(Fox_idle);
	Fox.setScale(4.0f, 4.0f);
	Fox.setTextureRect(sf::IntRect(0, 96, 128 / 4, 128));
	Fox.setPosition(8781, 7056);
	//Fox.setPosition(18000, 10000);
	Fox.setOrigin(Fox.getGlobalBounds().width / 2, Fox.getGlobalBounds().height / 2);
	idle_total_width = Fox_idle.getSize().x;
	idle_total_hight = Fox_idle.getSize().y;
	walking_total_width = Fox_walking.getSize().x;
	walking_total_hight = Fox_walking.getSize().y + 50;
	running_total_width = Fox_running.getSize().x;
	running_total_hight = Fox_running.getSize().y + 50;
	// Set up the hitbox for the fox, which is used for collision detection
	Fox_hitbox.setSize(sf::Vector2f(90, 70));
	Fox_hitbox.setFillColor(sf::Color::Transparent);
	//Fox_hitbox.setOrigin(Fox_hitbox.getSize().x / 2, Fox_hitbox.getSize().y / 2);
	// Load the textures for the main menu and game backgrounds, as well as a secondary background texture
	Game_Background[0].loadFromFile("MAIN/My-Fox/GUI/MAP1.png");
	Game_Background[1].loadFromFile("MAIN/My-Fox/GUI/MAP2.png");
	Game_Background[2].loadFromFile("MAIN/My-Fox/GUI/MAP3.png");
	Game_Background[3].loadFromFile("MAIN/My-Fox/GUI/MAP4.png");
	Game_Background_Sprite[0].setTexture(Game_Background[0]);
	Game_Background_Sprite[0].setPosition(0, 0);
	Game_Background_Sprite[1].setTexture(Game_Background[1]);
	Game_Background_Sprite[1].setPosition(Game_Background[0].getSize().x, 0);
	Game_Background_Sprite[2].setTexture(Game_Background[2]);
	Game_Background_Sprite[2].setPosition(0, Game_Background[0].getSize().y);
	Game_Background_Sprite[3].setTexture(Game_Background[3]);
	Game_Background_Sprite[3].setPosition(Game_Background[2].getSize().x, Game_Background[1].getSize().y);
	secondary_background_texture.loadFromFile("MAIN/My-Fox/GUI/image (1).png");
	secondary_background_sprite.setTexture(secondary_background_texture);

	// load the textures of animated Keys for menus
	W_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_W_1.png");
	A_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_A_1.png");
	S_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_S_1.png");
	D_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_D_1.png");
	Shift_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_Shift_1.png");
	E_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_button_E_1.png");
	Esc_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_Esc_1.png");
	W_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_W_2.png");
	A_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_A_2.png");
	S_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_S_2.png");
	D_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_D_2.png");
	Shift_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_Shift_2.png");
	E_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_button_E_2.png");
	Esc_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_Esc_2.png");
	P_texture[0].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_P_2.png");
	P_texture[1].loadFromFile("MAIN/My-Fox/GUI/Kb_buttons_P_1.png");
	W_sprite.setTexture(W_texture[0]);
	A_sprite.setTexture(A_texture[0]);
	S_sprite.setTexture(S_texture[0]);
	D_sprite.setTexture(D_texture[0]);
	Shift_sprite.setTexture(Shift_texture[0]);
	E_sprite.setTexture(E_texture[0]);
	Esc_sprite.setTexture(Esc_texture[0]);
	P_sprite.setTexture(P_texture[0]);

	Esc_sprite.setOrigin(Esc_sprite.getGlobalBounds().width / 2, Esc_sprite.getGlobalBounds().height / 2);
	Esc_sprite.setPosition(50, 50);
	Esc_sprite.setScale(2.0f, 2.0f);
	E_sprite.setOrigin(E_sprite.getGlobalBounds().width / 2, E_sprite.getGlobalBounds().height / 2);
	E_sprite.setScale(2.0f, 2.0f);
	W_sprite.setScale(2.0f, 2.0f);
	A_sprite.setScale(2.0f, 2.0f);
	S_sprite.setScale(2.0f, 2.0f);
	D_sprite.setScale(2.0f, 2.0f);
	Shift_sprite.setScale(2.0f, 2.0f);
	P_sprite.setScale(2.0f, 2.0f);
	W_sprite.setOrigin(W_sprite.getGlobalBounds().width / 2, W_sprite.getGlobalBounds().height / 2);
	A_sprite.setOrigin(A_sprite.getGlobalBounds().width / 2, A_sprite.getGlobalBounds().height / 2);
	S_sprite.setOrigin(S_sprite.getGlobalBounds().width / 2, S_sprite.getGlobalBounds().height / 2);
	D_sprite.setOrigin(D_sprite.getGlobalBounds().width / 2, D_sprite.getGlobalBounds().height / 2);
	Shift_sprite.setOrigin(Shift_sprite.getGlobalBounds().width / 2, Shift_sprite.getGlobalBounds().height / 2);
	P_sprite.setOrigin(P_sprite.getGlobalBounds().width / 2, P_sprite.getGlobalBounds().height / 2);
	W_sprite.setPosition(560, 440);
	A_sprite.setPosition(530, 470);
	S_sprite.setPosition(560, 470);
	D_sprite.setPosition(590, 470);
	Shift_sprite.setPosition(1050, 560);
	E_sprite.setPosition(1590, 635);
	P_sprite.setPosition(1350, 760);
	Esc_sprite1.setTexture(Esc_texture[0]);
	Esc_sprite1.setScale(2.0f, 2.0f);
	Esc_sprite1.setOrigin(Esc_sprite1.getGlobalBounds().width / 2, Esc_sprite1.getGlobalBounds().height / 2);
	Esc_sprite1.setPosition(1495, 755);

	Hare_texture.loadFromFile("MAIN/My-Fox/Animals/Hare/Hare_Idle_with_shadow.png");
	Deer_texture.loadFromFile("MAIN/My-Fox/Animals/Deer/Deer_Idle_with_shadow.png");
	Boar_texture.loadFromFile("MAIN/My-Fox/Animals/Boar/Boar_Idle_with_shadow.png");
	Black_grouse_texture.loadFromFile("MAIN/My-Fox/Animals/Black_grouse/Black_grouse_Idle_with_shadow.png");

	text_background_texture.loadFromFile("MAIN/My-Fox/GUI/rectangle-and-cricle-shape-solid-and-dot-outline-background-png.png");
	text_background_sprite.setTexture(text_background_texture);

	Sakura_texture.loadFromFile("MAIN/My-Fox/Trees/sakura-tree-1.png");
	Camp_fire_1_texture.loadFromFile("MAIN/My-Fox/decor/campfire1.png");
	Camp_fire_2_texture.loadFromFile("MAIN/My-Fox/decor/campfire2.png");
	Flag_texture.loadFromFile("MAIN/My-Fox/decor/flag.png");
	anvel.loadFromFile("MAIN/My-Fox/decor/anvel.png");
	fence.loadFromFile("MAIN/My-Fox/decor/fence.png");
	parallel_fence.loadFromFile("MAIN/My-Fox/decor/pixil-frame-0.png");
	box.loadFromFile("MAIN/My-Fox/decor/box.png");
	lake.loadFromFile("MAIN/My-Fox/decor/lake.png");
	well.loadFromFile("MAIN/My-Fox/decor/a well.png");
	car.loadFromFile("MAIN/My-Fox/decor/decor-1.png");
	light.loadFromFile("MAIN/My-Fox/decor/light.png");
	fallen_light.loadFromFile("MAIN/My-Fox/decor/light-fallen.png");
	broken_light.loadFromFile("MAIN/My-Fox/decor/light-broken.png");
	House.loadFromFile("MAIN/My-Fox/house/house-1.png");
	House_1.loadFromFile("MAIN/My-Fox/house/house-2.png");
	House_2.loadFromFile("MAIN/My-Fox/house/house-3.png");
	House_3.loadFromFile("MAIN/My-Fox/house/house-4.png");
	tent.loadFromFile("MAIN/My-Fox/house/tent-1.png");
	tent_1.loadFromFile("MAIN/My-Fox/house/tent-2.png");
	Tent_2.loadFromFile("MAIN/My-Fox/house/tent-3.png");
	Tent_3.loadFromFile("MAIN/My-Fox/house/tent-4.png");
	tree.loadFromFile("MAIN/My-Fox/trees/tree1.png");
	tree_1.loadFromFile("MAIN/My-Fox/trees/tree2.png");
	tree_2.loadFromFile("MAIN/My-Fox/trees/tree3.png");
	tree_3.loadFromFile("MAIN/My-Fox/trees/tree4.png");
	broken_tree.loadFromFile("MAIN/My-Fox/trees/Broken_tree1.png");
	broken_tree_1.loadFromFile("MAIN/My-Fox/trees/Broken_tree2.png");
	broken_tree_2.loadFromFile("MAIN/My-Fox/trees/Broken_tree3.png");
	broken_tree_3.loadFromFile("MAIN/My-Fox/trees/Broken_tree4.png");
	broken_tree_4.loadFromFile("MAIN/My-Fox/trees/Broken_tree5.png");
	broken_tree_5.loadFromFile("MAIN/My-Fox/trees/Broken_tree6.png");
	broken_tree_6.loadFromFile("MAIN/My-Fox/trees/Broken_tree7.png");
	Autumn_tree.loadFromFile("MAIN/My-Fox/trees/Autumn_tree1.png");
	Autumn_tree_1.loadFromFile("MAIN/My-Fox/trees/Autumn_tree2.png");
	Autumn_tree_2.loadFromFile("MAIN/My-Fox/trees/Autumn_tree3.png");
	christmas_tree.loadFromFile("MAIN/My-Fox/trees/christmas_tree1.png");
	Mossy_tree.loadFromFile("MAIN/My-Fox/trees/Moss_tree1.png");
	Mossy_tree_1.loadFromFile("MAIN/My-Fox/trees/Moss_tree2.png");
	Mossy_tree_2.loadFromFile("MAIN/My-Fox/trees/Moss_tree3.png");
	fruit_tree.loadFromFile("MAIN/My-Fox/trees/Fruit_tree2.png");
	fruit_tree_1.loadFromFile("MAIN/My-Fox/trees/Fruit_tree3.png");
	Burned_tree2.loadFromFile("MAIN/My-Fox/trees/Burned_tree2.png");
}